language: python

python:
  - 3.5

services: postgresql

env:
  - DJANGO=1.4.1

before_install:
  - export DJANGO_SETTINGS_MODULE=uc_app.settings
  - export PYTHONPATH=$HOME/builds/andrewmdinh/isa-project-ci
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet


script:
- python manage.py test