sudo: required

language: python

python:
  - 3.5

services: docker 

env:


before_install: 
  - docker pull tp33/django
  - docker pull mysql:5.7.14
  - docker start mysql 
  - docker ps -a
  - docker-compose up


install: true
# install:
#   - pip install -r requirements.txt
#   - pip install django==$DJANGO --quiet
#   - pip install psycopg2 --quiet


script:
  - python manage.py test