sudo: required

language: python

python:
  - 3.5

services: docker 


before_install: 
  - docker pull tp33/django
  - docker pull mysql:5.7.14
  - mkdir ~/db
  - docker run -it --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v ~/db:/var/lib/mysql  mysql:5.7.14
  - sleep 15
  - docker ps -a
  - docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.14 mysql -uroot -p'$3cureUS' -h db <<< "CREATE USER 'www'@'%' IDENTIFIED BY '\$3cureUS'; CREATE DATABASE test_cs4501; GRANT ALL ON test_cs4501.* to 'www'@'%';"
  # - create user 'www'@'%' identified by '$3cureUS';
  # - create database cs4501 character set utf8;
  # - grant all on cs4501.* to 'www'@'%';
  # - exit
  
install: true



script:
  - docker-compose up -d
  - docker ps -a 
  - docker exec -it models bash -c "python manage.py test"